In [13]:
import numpy as np

## 1. ndim과 shape

- `ndarray.ndim`: ndarray의 차원
- `ndarray.shape`: ndarray의 형태 (2차원의 경우, 행과 열의 수)

In [14]:
vec = np.array([1,2,3])
mat = np.array([[0,1,2,3],[4,5,6,7],[8,9,0,1]])
print(vec)
print(mat)

[1 2 3]
[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]


In [15]:
#ndim = 차원의 개수를 알려주는 속성. 숫자로 결과가 나옴
#0차원 (ndim = 0): 점 하나. 그냥 숫자 하나
#1차원 (ndim = 1): 직선 위의 점. 벡터라 함, 대괄호 [ ] 하나로 감싸져 - ex) 한 줄로 세운 데이터/ 1학년 1반 학생들의 키
#2차원 (ndim = 2): 평면 위의 점. 행렬이라 함. 대괄호 [ ]가 두 번 겹쳐 -ex) 행(가로)과 열(세로)이 있는 표 형태/ 1학년 1반의 국어, 영어, 수학 점수표
#차원 (ndim = 3): 입체 공간. 대괄호 [ ]가 세 번 겹쳐. 여러 개의 층으로 된 데이터 -ex) 1학년 1반, 2반, 3반 각 반의 국어, 영어 점수표
#point_ ndim: 배열의 차원 수 (중첩된 대괄호 [ ]의 개수
print(vec.ndim)
print(mat.ndim)

1
2


- `ndarray.ndim` 값은 `ndarray` 요소 값을 담는(시작 또는 끝나는 지점) 괄호의 수와 일치함

In [16]:
#Shape_ 각 차원(축)을 따라 얼마나 많은 요소가 있는지
#() 안에 숫자들이 나열됨. 이를 튜플이라 함

#0차원: () (튜플이 비어있음. 요소가 하나라서 '길이'가 없음)
#1차원 배열 [1, 2, 3, 4, 5]: shape은 (5,) (5개의 요소를 가진 1차원 배열)
#2차원 배열 [[1, 2, 3], [4, 5, 6]]: shape은 (2, 3) (2행 3열)
#첫 번째 차원(행, axis=0): 2개의 요소 ([1,2,3]과 [4,5,6])
#두 번째 차원(열, axis=1): 3개의 요소 (각 내부 배열의 1,2,3과 4,5,6)
#3차원 배열 [[[1,2], [3,4]], [[5,6], [7,8]]]: shape은 (2, 2, 2)
#첫 번째 차원(층, axis=0): 2개의 요소 (두 개의 [[1,2],[3,4]] 블록)
#두 번째 차원(행, axis=1): 2개의 요소 (각 블록 안의 [1,2]와 [3,4])
#세 번째 차원(열, axis=2): 2개의 요소 (가장 안쪽의 숫자 1,2와 3,4)
print(vec.shape)
print(mat.shape)

(3,)
(3, 4)


- `ndarray.shape`은 tuple 타입을 반환하며, tuple이 포함한 값의 수가 `ndarray.ndim`와 동일함
- 2차원 `ndarray.shape`의 경우, (**행의 수**, **열의 수**)

In [17]:
print(np.array(3).shape) # 괄호가 없으므로 ndim(차원)=0, shape이 반환하는 tuple의 값이 존재하지 않음
print(np.array([3]).shape) #1차원 (벡터), 첫 번째 차원에 1개의 요소 → (1,) +)튜플에서 쉼표는 단일 요소 튜플 의미
print(np.array([[3]]).shape) #2차원 (행렬), 첫 번째 차원(행)에 1개의 요소, 두 번째 차원(열)에 1개의 요소 so, 1×1 크기의 표 (셀 하나)
print(np.array([[[[[3]]]]]).shape) #5차원, 5개의 차원 각각에 1개의 요소, 5차원 공간에서 한 점의 좌표

()
(1,)
(1, 1)
(1, 1, 1, 1, 1)


## 2. indexing과 slicing

- **indexing**: `ndarray[a,b]`
- **slicing**: `ndarray[a:b,c:d]`
> - `a:b` index a부터 b-1까지 (b를 포함하지 않음)
> - `a:` index a부터 마지막 index(-1)까지
> - `:b` index 0(첫 index)부터 b-1까지
> - `:` 모든 index
> - `a:b`에서 `b`가 마지막 index보다 큰 값일 경우, 마지막 index까지를 포함함

In [18]:
print(mat)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]


In [19]:
# mat[행 index, 열 index]
mat[1,2]

np.int64(6)

In [20]:
# slicing = 0,1행 / 1,2,3열
# [[1,2,3],
#  [5,6,7]]
print(mat[0:2,1:4]) #0:2 = 0행, 1행 / 1:4 = 1열, 2열, 3열
print(mat[ :2,1: ]) #:2 = 처음부터 1행까지 / 1열부터 마지막 열(3열)

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [5 6 7]]


- `ndarray[index,index]`(indexing): 0차원
- `ndarray[index,범위]` 또는 `ndarray[범위,index]`(slicing): 1차원
- `ndarray[범위,범위]`(slicing): 2차원

In [21]:
#값을 꺼내는 행위= mat 배열에서 1행 2열 위치에 있는 실제 값을 꺼내서 보여줘
print(mat[1,2]) #행(1)과 열(2)을 정수로 지정 → 차원이 2개 축소
print(mat[1:2,2])   # 1:2는 index 1만 포함하는 범위 / 2열에서 1행만 선택 → 한 줄의 데이터
print(mat[1,2:3])   # 2:3은 index 2만 포함하는 범위 /1행에서 2열만 선택 → 한 줄의 데이터
print(mat[1:2,2:3]) #1:2 = 1행만 선택 (but 범위로 선택했으므로 차원 유지), 2:3 = 2열만 선택 (but 범위로 선택했으므로 차원 유지) /1행2열의 작은 표(1×1)를 추출

6
[6]
[6]
[[6]]


In [22]:
#꺼낸 것의 형태를 확인하는 행위= 방금 꺼낸 그 것의 형태(shape)가 어떻게 생겼어?
print(mat[1,2].shape) #2차원 배열에서 0차원 스칼라 값이 됨(차원축소)= mat은 2차원, 1행을 선택함으로서 1차원으로 축소, 2열을 선택함으로서 0차원으로 축소
print(mat[1:2,2].shape)   # 1:2는 index 1만 포함하는 범위
print(mat[1,2:3].shape)   # 2:3은 index 2만 포함하는 범위
print(mat[1:2,2:3].shape)

()
(1,)
(1,)
(1, 1)


## 3. reshape

- `ndarray.shape(변경하고자하는 shape)`
핵심 개념: 데이터는 그대로 있고, 보여지는 형태만 바꾸는 작업

In [23]:
print(mat)
print(mat.shape)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]
(3, 4)


In [24]:
print(mat.reshape(4,3))
#원래 3줄×4개씩 놓여있던 블록을 4줄×3개씩 재배열
#데이터 순서는 유지된 채로 형태만 바뀜! so, 잘 안 씀- 아예 정보가 달라지기에(행과 열의) +) 행과 열을 바꾸는 건 transpose

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 1]]


- 전체 원소의 수가 다를 경우, 오류 발생

In [25]:
mat.reshape(3,3) ## 3×3 = 9 → 하지만 실제 블록은 12개!

ValueError: cannot reshape array of size 12 into shape (3,3)

- `reshape(a,b)`에서 a*b는 반드시 원소의 수와 동일해야 하지만, 둘 중 하나를 -1로 지정하면, 자동으로 원소의 수를 맞춰 reshape함
> - 예를 들어, `(3,4)`인 2darray에 `reshape(2,-1)`를 적용하면, `(2,6)`으로 변형됨
- `reshape`을 통한 차원의 변경
> - `reshape(1,-1)`: 1행 n열의 2차원으로 변경
> - `reshape(-1,1)`: n행 1열의 2차원으로 변경
> - `reshape(-1)`: 1차원으로 변경

In [33]:
print(vec)
print(vec.reshape(-1,1)) #의미:행은 알아서 계산하고, 열은 1개로 만들어/ 비유: 가로로 놓인 블록을 세로로 세우기
print(vec.reshape(1,-1)) #의미:행은 1개로 하고, 열은 알아서 계산해/ 비유: 데이터를 한 줄로 펼쳐놓기
print(mat.reshape(-1)) #의미:차원 신경쓰지 말고 그냥 일렬로 세워/ 비유: 레고 블록을 한 줄로 나열하기

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[0 1 2 3 4 5 6 7 8 9 0 1]


In [34]:
#마법의 숫자: -1 (자동 계산)
#-1은 '남은 블록 다 여기에 넣어!'라는 의미
print(mat)
print(mat.reshape(-1))

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]
[0 1 2 3 4 5 6 7 8 9 0 1]


In [35]:
# 원본: (3, 4) = 12개 블록

# 2행으로 나눌 때 각 행에 몇 개씩?
print(mat.reshape(2, -1))  # → (2, 6) : 2행×6열 = 12개
# "2행으로 나눌게, 남은 블록은 알아서 계산해!"

# 4열로 나눌 때 몇 행이 필요?
print(mat.reshape(-1, 4))  # → (3, 4) : 3행×4열 = 12개
# "4열로 나눌게, 필요한 행 수는 알아서 계산해!"

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]


In [36]:
import numpy as np

arr1 = np.array([1, 2, 3]) #1치원 배열(벡터)
print("배열:", arr1)
print("Shape:", arr1.shape)      # (3,)
print("차원 수:", arr1.ndim)     # 1
print("크기:", arr1.size)        # 3
print("전체 구조:")
print(arr1)

배열: [1 2 3]
Shape: (3,)
차원 수: 1
크기: 3
전체 구조:
[1 2 3]


In [37]:
arr2 = np.array([[1, 2, 3]])  #2차원 배열 (1×3 행렬) +)(1행 n열)
print("배열:", arr2)
print("Shape:", arr2.shape)      # (1, 3)= 1행 3열
print("차원 수:", arr2.ndim)     # 2
print("크기:", arr2.size)        # 3
print("전체 구조:")
print(arr2)

배열: [[1 2 3]]
Shape: (1, 3)
차원 수: 2
크기: 3
전체 구조:
[[1 2 3]]


In [39]:
arr3 = np.array([[1], [2], [3]])  #2차원 배열 (3×1 행렬) +)(n행 1열)
print("배열:", arr3)
print("Shape:", arr3.shape)      # (3, 1)= 3행 1열
print("차원 수:", arr3.ndim)     # 2
print("크기:", arr3.size)        # 3
print("전체 구조:")
print(arr3)

배열: [[1]
 [2]
 [3]]
Shape: (3, 1)
차원 수: 2
크기: 3
전체 구조:
[[1]
 [2]
 [3]]


- `ndarray.T` 또는 `ndarray.transpose()`: transpose (행 -> 열, 열 -> 행으로 변환)
> - `ndarray.shape`이 `(n,m)`일 때, `reshape(m,n)`과 `T`(transpose) 모두 결과의 shape는 `(m,n)`으로 동일하지만, value의 배치는 다름을 기억할 것
> - `reshape(m,n)`은 행과 열이 섞이면서 정보를 잃기 때문에, 잘 사용하지 않음

In [40]:
print(mat.T)
print(mat.T.shape)

[[0 4 8]
 [1 5 9]
 [2 6 0]
 [3 7 1]]
(4, 3)


## 4. delete와 concatenate
- `np.delete(ndarray,index,axis)`
> - `index`: 삭제하고자하는 행 또는 열의 index
> - `axis`: 행 또는 열 지정
- `np.concatenate((ndarray1,ndarray2),axis)`
> - `ndarray1, ndarray2`: 결합할 두 ndarray
> - `axis`: 결합 방향(행 또는 열 방향)

np.delete에 axis를 지정하지 않는 경우, ndarray의 value를 1d로 나열한 후, 지정된 index의 값을 삭제하고, 1d array로 반환함 (거의 사용하지 않음)
ndarray는 특정 위치의 값이 NULL 또는 NaN일 수 없다

In [41]:
np.delete(mat,2)

array([0, 1, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [42]:
# axis=0은 행을 삭제하라는 의미
# -> 데이터 샘플의 삭제
# -> ex> 성적 데이터에서 특정 학생의 정보를 삭제
np.delete(mat,2,axis=0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
# axis=1은 열을 삭제하라는 의미
# -> 특징의 삭제
# -> ex> 성적 데이터에서 특정 과목 점수를 삭제
np.delete(mat,2,axis=1)

array([[0, 1, 3],
       [4, 5, 7],
       [8, 9, 1]])

In [44]:
mat2 = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]])
print(mat2)
print(mat2.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
(3, 4)


In [45]:
# 2d array의 경우, axis=0으로 설정하면, 상하로 결합됨
# axis=0: 행과 행이 결합됨, 데이터 샘플의 추가
#         ex> 성적 데이터에서 신규 학생 데이터를 추가
# axis는 디폴트로 0으로 설정되어 있음
np.concatenate((mat,mat2),axis=0)
# 또는 np.concatenate((mat,mat2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [46]:
# 2d array의 경우, axis=1로 설정하면, 좌우로 결합됨
# axis=1: 열과 열이 결합됨, 특징의 추가
#         ex> 성적 데이터에서 신규 과목 점수를 추가
np.concatenate((mat,mat2),axis=1)

array([[0, 1, 2, 3, 0, 0, 0, 0],
       [4, 5, 6, 7, 1, 1, 1, 1],
       [8, 9, 0, 1, 2, 2, 2, 2]])

## 5. ndarray의 연산(곱)
- `arr1*arr2`: 각 요소의 곱이 반환
- `arr1.dot(arr2)`: 행렬의 곱
> - **`2d array` 기준으로 `arr1`의 열과, `arr2`의 행이 동일해야 함**
> - `arr1.shape`= **(m,n)**, `arr2.shape`= **(n,k)** 일 때, `arr1.dot(arr2)`의 결과는 **(m,k)**

In [47]:
print(mat, mat.shape)
print(mat2, mat.shape)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]] (3, 4)
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]] (3, 4)


In [48]:
mat*mat2

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18,  0,  2]])

In [49]:
mat.dot(mat2)
# mat의 열과 mat2의 행이 다르므로 행렬의 곱이 성립되지 않음

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [50]:
mat.dot(mat2.T)
# mat.shape=(3,4)
# mat2.T.shape=(4,3)

array([[ 0,  6, 12],
       [ 0, 22, 44],
       [ 0, 18, 36]])