In [16]:
import numpy as np

In [17]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
print(X.shape)

#(행의 수, 열의 수)

(4, 2)


- `X.shape[0]`: 데이터 샘플의 수_ 행의 개수


- `X.shape[1]`: 특징의 수 (입력 노드의 수)_ 열의 개수

- 인자가 **(입력, 가중치, 편향)** 이며, **0** 또는 **1**을 반환하는  `perceptron` 함수 정의
- **입력**은 `2d array` 타입으로, **데이터 샘플의 수만큼 값을 반환**함

- `A.dot(B)` = 행렬 곱셈
> - `A.shape[1]`과 `B.shape[0]`은 반드시 일치해야 함_
A의 열 수 == B의 행 수 여야만 곱셈 가능하다는 말
> - `A.dot(B).shape`은 `(A.shape[0], B.shape[1])` </br>
단, `B`가 1d array인 경우, 결과는 `(A.shape[0], )`임

- `X.shape`=`(4,2)`, `w.shape`=`(2,)`일 때,
> - `X.shape[1] = 2`, `w.shape[0] = 2`로 일치함
> - `X.dot(A).shape` = `(4,)`
> - `X.shape[0] = 4`는 데이터샘플 수를 의미하며, 입력이 4개의 샘플이므로, 각 샘플에 대한 결과값을 반환하므로 출력도 4개임

- 2D 배열 × 1D 배열

X = np.array([[0,0], [0,1], [1,0], [1,1]])  # shape: (4, 2)

w = np.array([1, 2])                         # shape: (2,)

print("X.dot(w) shape:", X.dot(w).shape)     # (4,)

결과: [0, 2, 1, 3]

- `X`는 `ndarray`, `b`는 `dim`이 0인 상수 또는 변수일 때,(ex> `b=1`), </br>
`X + b`를 수행하면, `X`의 모든 요소에 대해 `b`가 더해진다.

In [18]:
print(X)
w = np.array([1,2])
print(X.dot(w))
b = -1 #_ 여기서 b는 스칼라(숫자 하나)
print(X.dot(w)+b)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 2 1 3]
[-1  1  0  2]


In [19]:
#+) 위의 코드 해설

b = -1  # 이것이 스칼라입니다!

# 스칼라 b를 벡터에 더하기
vector = np.array([0, 2, 1, 3])  # X.dot(w) 결과
scalar = -1

result = vector + scalar
print(result)  # [-1, 1, 0, 2]

[-1  1  0  2]


- `if X.dot(w)+b > 0:` 는 `X.dot(w)+b`가 복수의 요소를 포함하는 `ndarray`이므로 `True/False`를 하나로 정의할 수 없음 (오류발생)
- `return X.dot(w)+b > 0`: `X.dot(w)+b`의 각 요소에 대해 `True/False`를 반환
- 결과를 `True/False`가 아닌 `int` 타입의 수로 반환을 원하는 경우, `astype`으로 타입을 강제 변환함

## 1. perceptron 정의

In [20]:
def perceptron(X,w,b):
    # return X.dot(w)+b > 0
    return (X.dot(w)+b > 0).astype('int')

    #0보다 큰지 확인 후 0/1로 변환:
   #[-1  1  0  2] > 0 = [0 1 0 1]

In [21]:
perceptron(X,w,b)

array([0, 1, 0, 1])

## 2. AND, NAND, OR 정의

### (1) AND 함수 정의_ "둘 다 참이어야 참" 두 입력이 모두 1일 때만 출력이 1
- `w = [1.5,1]`, `b = -2`

In [31]:
def AND(input):
    w = np.array([1.5,1])  #가중치
    b = -2  #편향
    return perceptron(input,w,b)

    print(AND(X))

In [ ]:
#   print(AND(X))의 출력값 = (0,0,0,1)

#AND 게이트:
#방정식: 1.5*x1 + 1*x2 - 2 = 0
#1.5*x1 + x2 = 2 선 위에 있을 때만 1

#입력: (0,0) → 0×1.5 + 0×1 + (-2) = -2 → 0 (False)
#입력: (0,1) → 0×1.5 + 1×1 + (-2) = -1 → 0 (False)
#입력: (1,0) → 1×1.5 + 0×1 + (-2) = -0.5 → 0 (False)
#입력: (1,1) → 1×1.5 + 1×1 + (-2) = 0.5 → 1 (True)

### (2) NAND 함수 정의_ AND의 정반대 결과 "둘 다 참이면 거짓"
- `w = [-2,-2]`, `b = 3`

In [23]:
def NAND(input):
    w = np.array([-2,-2]) # 가중치 (음수!)
    b = 3   # 편향 (양수!)
    return perceptron(input,w,b)

In [32]:
# print(NAND)의 출력값 = (1,1,1,0)

#NAND 게이트:
#방정식: -2*x1 - 2*x2 + 3 = 0
#-2*x1 - 2*x2 = -3 선 위에 있을 때 1

#입력: (0,0) → 0×(-2) + 0×(-2) + 3 = 3 → 1 (True)
#입력: (0,1) → 0×(-2) + 1×(-2) + 3 = 1 → 1 (True)
#입력: (1,0) → 1×(-2) + 0×(-2) + 3 = 1 → 1 (True)
#입력: (1,1) → 1×(-2) + 1×(-2) + 3 = -1 → 0 (False)

 ### (3) OR 함수 정의 _ "하나라도 참이면 참" 두 입력 중 하나라도 1이면 출력이 1
- `w = [2,2]`, `b = -1`

In [24]:
def OR(input):
    w = np.array([2,2])
    b = -1
    return perceptron(input,w,b)

In [ ]:
# print(NAND)의 출력값 = (0.1.1.1)

#OR 게이트:
#방정식: 2*x1 + 2*x2 - 1 = 0
#2*x1 + 2*x2 = 1 선 위에 있을 때 1

#입력: (0,0) → 0×2 + 0×2 + (-1) = -1 → 0 (False)
#입력: (0,1) → 0×2 + 1×2 + (-1) = 1 → 1 (True)
#입력: (1,0) → 1×2 + 0×2 + (-1) = 1 → 1 (True)
#입력: (1,1) → 1×2 + 1×2 + (-1) = 3 → 1 (True)

### (4) X에 대한 AND/NAND/OR 출력 확인

In [25]:
print(AND(X), NAND(X), OR(X))

[0 0 0 1] [1 1 1 0] [0 1 1 1]


## 3. XOR 정의

### (1) AND/NAND/OR 를 이용한 XOR 정의_ 특징: 두 입력이 다를 때만 1, 같으면 0

AND, OR, NAND는 직선 하나로 구분 가능

XOR은 직선 하나로 구분 불가능

XOR을 구현하려면 은닉층(Hidden Layer) 이 필요 SO, 다층 퍼셉트

In [26]:
def XOR(input):
    s1 = NAND(input) # NAND 결과_ [1, 1, 1, 0] / so,1D 배열 shape: (4,)
    s2 = OR(input)  # OR 결과_ [0, 1, 1, 1] / so, 2D 배열 shape: (4,)

    # AND의 입력은 s1과 s2가 결합된 (4,2) shape이 되어야 함/ why? AND는 2D를 원하기에
    # 1. s1과 s2를 (4,1) shape으로 변환
    s1_r = s1.reshape(-1,1)  # shape: (4, 1)
    s2_r = s2.reshape(-1,1)  # shape: (4, 1)
    print(s1_r)= [1,1,1,0]
    print(s2_r)= [0,1,1,1]

    # 2. shape이 변경된 s1과 s2를 좌우(axis=1)결합
    input_and = np.concatenate((s1_r,s2_r),axis=1)
    return AND(input_and)
    print(input_and)= [[1,0]
                        [1,1]
                        [1,1]
                        [0,1]]
# def XOR(input):
#     return AND(np.concatenate((NAND(input).reshape(-1,1),OR(input).reshape(-1,1)),
#                               axis=1))

### (2) X에 대한 XOR 출력 확인

In [27]:
XOR(X)

array([0, 1, 1, 0])

In [ ]:
#입력 X (4,2)
#   ↓
#[NAND] → s1 (4,) → reshape → s1_r (4,1)
#[OR]   → s2 (4,) → reshape → s2_r (4,1)
#    ↓
#concatenate(axis=1) → input_and (4,2)
#    ↓
#[AND] → 최종 출력 (4,)
#    ↓
#[0, 1, 1, 0] (XOR 완성!)